In [1]:
import numpy as maths
import warnings
warnings.filterwarnings("ignore")

# Questions

In [16]:
vars = 2

In [49]:
c = [2,3]
conditions = [
    [1,1],
    [5,3]
]

signs = ['lte','gte']

b = [4,8]

In [50]:

if len(conditions) == len(b):
    size = len(conditions)
    c = maths.array(c).reshape(-1,1)
    original_constraints = maths.vstack(( c,maths.zeros((size,1)) ))
    D = maths.matrix(conditions)
    b = maths.array(b).reshape(-1,1)
    print(D)
    print(b)
else :
    print("Conditions or Answers are not Correct !!!")

[[1 1]
 [5 3]]
[[4]
 [8]]


## Phase I

In [51]:
surplus_vars = signs.count('gte')

In [52]:
c = maths.ones(surplus_vars).reshape(-1,1)

In [53]:
if surplus_vars == 1 : surplus_matrix = maths.vstack((maths.zeros((len(b) - surplus_vars,1)).reshape(-1,1),-maths.ones(surplus_vars).reshape(-1,1)))
else : surplus_matrix = -maths.identity(surplus_vars)
D = maths.hstack((D,surplus_matrix))
print(D)

[[ 1.  1.  0.]
 [ 5.  3. -1.]]


# Algorithm

## Initialisations

2

In [68]:
vars + surplus_vars

3

In [54]:
B = maths.identity(size)
A = maths.hstack((B,D))
c = maths.vstack((maths.zeros((vars + surplus_vars,1)),c))

x = maths.vstack(( maths.zeros((vars + surplus_vars,1)) , b ) )
order = list(maths.arange(vars + surplus_vars+1,len(x)+1,1)) + list(maths.arange(1,vars + surplus_vars+1,1))

## Reduced Cost Coefficients

In [55]:
Ab = maths.hstack((A,b.reshape(-1,1)))
Ab

matrix([[ 1.,  0.,  1.,  1.,  0.,  4.],
        [ 0.,  1.,  5.,  3., -1.,  8.]])

In [56]:
print("Initial Solution :",x.T)
r = c - A.T @ c[-surplus_vars:]
# r = c - A.T @ c[-size:]


print()
print("Initial Ab")
print(Ab)

p = 0
q = 1


while (r[size:] < 0 ).any() and p != q:
       
    ## Updation
    q = maths.argmin(r)
    p = maths.argmin(Ab[:,-1]/Ab[:,q])
    print("Column",p,"is replaced with",q)
    
    print()
    
    ## Row Operations
    m , n = Ab.shape
    for i in range(m):
        if i != p : Ab[i] = Ab[i] - ( (Ab[i,q]/Ab[p,q]) * Ab[p] )
    Ab[p] = Ab[p] / Ab[p,q]
    Ab[:,p] , Ab[:,q] = Ab[:,q].copy() , Ab[:,p].copy()
    print(maths.round(Ab,2))
    
    
    ## Update Constraints
    c[p] , c[q] = c[q].copy(), c[p].copy()
    order[p] , order[q] = order[q].copy() , order[p].copy()
    print(order)    
    x = maths.zeros(len(x)).reshape(-1,1)
    x[:size] = Ab[:,-1]
    
    solution = []
    for i in range(len(order)):
        solution.append(float(x[order.index(i+1)]))
    x = maths.array(solution)
       
    
    ## Update Reduced Cost Coefficients
    r = c - Ab[:,:-1].T @ c[-surplus_vars:]
    
    print("Present Solution is :",x.T)
    print()
print("Final Optimal Solution ",x.T)

Initial Solution : [[0. 0. 0. 4. 8.]]


ValueError: operands could not be broadcast together with shapes (4,1) (5,1) 

In [43]:
b = Ab[:,-1]
Ab = Ab[:,:-1]

Ab_copy = Ab.copy()

for i in range(len(order)): Ab_copy[:,i] = Ab[:,order.index(i+1)-1] 
Ab = Ab_copy.copy()

A = Ab[:,:vars + surplus_vars]
Ab = maths.hstack((A,b))

# Phase II

In [45]:
if len(conditions) == len(b):
    c = original_constraints[:vars]
    D = maths.matrix(conditions)
    b = maths.array(b).reshape(-1,1)
    print(D)
    print(b)
else :
    print("Conditions or Answers are not Correct !!!")

[[4 2]
 [1 4]]
[[2.57142857]
 [0.85714286]]


In [46]:
c = maths.vstack(( maths.zeros((size,1)) , c ))
x = maths.vstack(( maths.zeros((vars,1)) , b ) )
order = list(maths.arange(vars+1,len(x)+1,1)) + list(maths.arange(1,vars+1,1))

## Reduced Cost Coefficients

In [47]:
print("Initial Solution :",maths.round(x.T))
r = c - A.T @ c[:size]

print()

print(maths.round(Ab,2))

while (r[size:] < 0 ).any():
       
    ## Updation
    q = maths.argmin(r)
    p = maths.argmin(Ab[:,-1]/Ab[:,q])
    print("Column",p,"is replaced with",q)
    
    print()
    
    ## Row Operations
    m , n = Ab.shape
    for i in range(m):
        if i != p : Ab[i] = Ab[i] - ( (Ab[i,q]/Ab[p,q]) * Ab[p] )
    Ab[p] = Ab[p] / Ab[p,q]
    Ab[:,p] , Ab[:,q] = Ab[:,q].copy() , Ab[:,p].copy()
    print(Ab)
    
    
    ## Update Constraints
    c[p] , c[q] = c[q].copy(), c[p].copy()
    order[p] , order[q] = order[q].copy() , order[p].copy()
    
    x = maths.zeros(len(x)).reshape(-1,1)
    x[:size] = Ab[:,-1]
    
    solution = []
    for i in range(len(order)):
        solution.append(float(x[order.index(i+1)]))
    x = maths.array(solution)
       
    
    ## Update Reduced Cost Coefficients
    r = c - Ab[:,:-1].T @ c[:size]
    
    print("Present Solution is :",maths.round(x.T,2))
    print()
x_copy = maths.zeros(len(x))
for i in range(len(x)): x_copy[i] = x[order.index(i+1)]
x = x_copy.copy()

print()
print("Final Optimal Solution ",maths.round(x.T,2))

Initial Solution : [[0. 0. 3. 1.]]

[[ 0.14  1.   -0.14 -0.29  2.57]
 [-0.29  0.    0.29  0.07  0.86]]

Final Optimal Solution  [2.57 0.86 0.   0.  ]


In [48]:
print("Final Solution : ",maths.round(x.T[:vars],2))
print("Objective :",round(float(original_constraints.T @ x),2))

Final Solution :  [2.57 0.86]
Objective : 7.71
