In [18]:
import numpy as maths
import warnings
warnings.filterwarnings("ignore")

# Questions

In [24]:
vars = 2
vars = maths.zeros(vars)

In [34]:
c = [-2,-3]
coefficients = [
    [4,2],
    [1,4]
]
conditions = ['gte','gte']
b = [12,6]

In [ ]:
gtes = 0
ltes = 0
for i in range(len(conditions)):
    if conditions[i] == 'gte': gtes = gtes + 1
    else : ltes = ltes + 1

for i in range(gtes):
    coefficients[i].append(maths.zeros(gtes))
    

In [36]:
list(maths.zeros(2))

[0.0, 0.0]

In [28]:
if len(coefficients) == len(b):
    c = maths.array(c).reshape(-1,1)
    D = maths.matrix(coefficients)
    b = maths.array(b).reshape(-1,1)
    print(D)
    print(b)
else :
    print("Conditions or Answers are not Correct !!!")

[[4 2]
 [1 4]]
[[12]
 [ 6]]


# Algorithm

## Initialisations

In [29]:
size = len(coefficients)
B = maths.identity(size)
A = maths.hstack((B,D))
original_constraints = maths.vstack(( c,maths.zeros((size,1)) ))
c = maths.vstack(( maths.zeros((size,1)) , c ))
x = maths.vstack(( maths.zeros((len(vars),1)) , b ) )
order = list(maths.arange(len(vars)+1,len(x)+1,1)) + list(maths.arange(1,len(vars)+1,1))

## Canonical Form

In [30]:
Ab = maths.hstack((A,b.reshape(-1,1)))
Ab

matrix([[ 1.,  0.,  4.,  2., 12.],
        [ 0.,  1.,  1.,  4.,  6.]])

## Reduced Cost Coefficients

In [31]:
print("Initial Solution :",x.T)
r = c - A.T @ c[:size]

print()

print(Ab)

while (r[size:] < 0 ).any():
       
    ## Updation
    q = maths.argmin(r)
    p = maths.argmin(Ab[:,-1]/Ab[:,q])
    print("Column",p,"is replaced with",q)
    
    print()
    
    ## Row Operations
    m , n = Ab.shape
    for i in range(m):
        if i != p : Ab[i] = Ab[i] - ( (Ab[i,q]/Ab[p,q]) * Ab[p] )
    Ab[p] = Ab[p] / Ab[p,q]
    Ab[:,p] , Ab[:,q] = Ab[:,q].copy() , Ab[:,p].copy()
    print(Ab)
    
    
    ## Update Constraints
    c[p] , c[q] = c[q].copy(), c[p].copy()
    order[p] , order[q] = order[q].copy() , order[p].copy()
    
    x = maths.zeros(len(x)).reshape(-1,1)
    x[:size] = Ab[:,-1]
    
    solution = []
    for i in range(len(order)):
        solution.append(float(x[order.index(i+1)]))
    x = maths.array(solution)
       
    
    ## Update Reduced Cost Coefficients
    r = c - Ab[:,:-1].T @ c[:size]
    
    print("Present Solution is :",x.T)
    print()
print("Final Optimal Solution ",x.T)

Initial Solution : [[ 0.  0. 12.  6.]]

[[ 1.  0.  4.  2. 12.]
 [ 0.  1.  1.  4.  6.]]
Column 1 is replaced with 3

[[ 1.    0.    3.5  -0.5   9.  ]
 [ 0.    1.    0.25  0.25  1.5 ]]
Present Solution is : [0.  1.5 9.  0. ]

Column 0 is replaced with 2

[[ 1.          0.          0.28571429 -0.14285714  2.57142857]
 [ 0.          1.         -0.07142857  0.28571429  0.85714286]]
Present Solution is : [2.57142857 0.85714286 0.         0.        ]

Final Optimal Solution  [2.57142857 0.85714286 0.         0.        ]


In [33]:
print("Objective :",float(original_constraints.T @ x))

Objective : -7.714285714285715
